# Generated by Django 2.0.5 on 2018-06-07 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180605_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 12, 19, 39, 139123, tzinfo=utc)),
        ),
    ]
